name: Validate Secret

on:
  push:
    branches:
      - main  # Cambia esto a la rama en la que quieres que se ejecute el flujo de trabajo

jobs:
  validate-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Secret
        run: |
          # Obtener el valor del secreto
          SECRET_VALUE="${{ secrets.MY_SECRET }}"
          
          # Validar el valor del secreto (puedes personalizar esta lógica)
          if [ "$SECRET_VALUE" == "secret_wrong_value" ]; then
            echo "El secreto correcto."
          else
            echo "El secreto incorrecto. Valor actual: $SECRET_VALUE"
            exit 1
          fi
